# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ScanForVulnerabilities@0
  inputs:
    ProjectFileName: 'TestApplication.csproj'
    VulnerabilityAction: 'Fail'

- task: ScanForVulnerabilities@0
  inputs:
    ProjectFileName: 'Data.csproj'
    VulnerabilityAction: 'Fail'

- task: ScanForVulnerabilities@0
  inputs:
    ProjectFileName: 'Scan.csproj'
    VulnerabilityAction: 'Fail'

- task: ScanForVulnerabilities@0
  inputs:
    ProjectFileName: 'VisualStudioExtension.csproj'
    VulnerabilityAction: 'Fail'

- task: ScanForVulnerabilities@0
  inputs:
    ProjectFileName: 'ModelGenerator.csproj'
    VulnerabilityAction: 'Fail'